### PR TITLE
:wastebasket: Removal of deprecated, unused functions.

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :wastebasket: Removal of deprecated, unused functions.

/kind cleanup

Follow up on #294

### CODE REVIEW

**Comment by cardil** [comment]
The failing downstream tests are because of #294 and are covered by the following PRs:

- knative-sandbox/eventing-kafka-broker#2413
- knative-sandbox/eventing-natss#348
- knative-sandbox/eventing-rabbitmq#867
- knative-sandbox/kn-plugin-event#203
- https://github.com/knative-sandbox/discovery/pull/280

**Review by upodroid — APPROVED** [review]
LGTM, thank you for the changes to logging

/approve
/hold 

Cancel the hold when you are ready.

**Comment by cardil** [comment]
Let's proceed. Merging it will not influence the downstream projects further.

/unhold

**Pull request merged**
