### PR TITLE
import release 0.26 dependencies

### PR DESCRIPTION
**Pull request by ZhiminXiang**

### CODE REVIEW

**Comment by rhuss** [comment]
@ZhiminXiang some tests are failing, but just curious: Why is the dependency not automatically updated by knobots ?

**Comment by ZhiminXiang** [comment]
> @ZhiminXiang some tests are failing, but just curious: Why is the dependency not automatically updated by knobots ?

not sure. I tried to kick out the automatic update from knobots, but could not successfully make it work.

**Comment by ZhiminXiang** [comment]
The tests are now good. Ready for review.

**Pull request merged**
