### PR TITLE
Update to post 0.19 release

### PR DESCRIPTION
**Pull request by n3wscott**
# Changes

- :broom: Drop test-infra.

/kind cleanup

### CODE REVIEW

**Comment by n3wscott** [comment]
Followup to https://github.com/knative-sandbox/reconciler-test/pull/46

**Comment by vaikas** [comment]
lint fails on misspellings in the vendor?
```
  reviewdog: Reporting results for "github.com/client9/misspell"
  Error: [github.com/client9/misspell] reported by reviewdog 🐶
  "functionallity" is a misspelling of "functionality"
  
  Raw Output:
  vendor/knative.dev/hack/README.md:4:11: "functionallity" is a misspelling of "functionality"
  Error: [github.com/client9/misspell] reported by reviewdog 🐶
  "functionallity" is a misspelling of "functionality"
  
  Raw Output:
  vendor/knative.dev/hack/hack.go:20:26: "functionallity" is a misspelling of "functionality"
  Error: Process completed with exit code 1.
```

/lgtm
/approve

**Pull request merged**
