### PR TITLE
:bug: Eventshub tests work on Windows

### LINKED ISSUE #337: The tests fail while using eventshub when executed on Windows machine
The tests fail catastrophically while using _eventhub_ component, while being executed on Windows machine.

Error log:

```log
2022/05/11 12:37:51 new files in C:\Users\hudson\AppData\Local\Temp\processed_yaml2044020863
I0511 12:37:51.281097    6776 manifest.go:62] Reading YAML filepath: C:\Users\hudson\AppData\Local\Temp\processed_yaml2044020863 recursive: false
    rbac.go:35: Get "c:\\Users\\hudson\\AppData\\Local\\Temp\\processed_yaml2044020863": unsupported protocol scheme "c"
```

Fatal invocation:

https://github.com/knative-sandbox/reconciler-test/blob/776888f76c76d761f0dd707e4ccb2a65bb0eada8/pkg/eventshub/rbac/rbac.go#L35

/kind bug

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: Eventshub tests work on Windows

/kind bug

Fixes #337

## Release Note

```release-note
 - The tests that utilizes Eventshub component will now work properly while executed from Windows machine.
```

## Caveats

 - relies on the #294

### CODE REVIEW

**Comment by cardil** [comment]
The 9be0708 fixes the manifest parsing on Windows #337 as confirmed by CI run https://github.com/knative-sandbox/reconciler-test/runs/7240001521?check_suite_focus=true

**Comment by cardil** [comment]
All tests on Windows passed:

```
DONE 97 tests in 442.271s
```

**Comment by cardil** [comment]
The failing downstream tests are because of #294 and are covered by the following PRs:

- knative-sandbox/eventing-kafka-broker#2413
- knative-sandbox/eventing-natss#348
- knative-sandbox/eventing-rabbitmq#867
- knative-sandbox/kn-plugin-event#203
- https://github.com/knative-sandbox/discovery/pull/280

**Review by upodroid — APPROVED** [review]
/hold

Cancel hold when you are ready to merge.

**Comment by cardil** [comment]
Let's proceed. Merging it will not influence the downstream projects further.

/unhold

**Pull request merged**
