### PR TITLE
print all the headers, including ce-*

### PR DESCRIPTION
**Pull request by vaikas**
# Changes

- Print all the headers (including ce-* headers) so that it's easier to see what was actually sent.

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by vaikas** [comment]
Failing with:

https://github.com/knative-sandbox/reconciler-test/pull/155/checks?check_run_id=2188512815

```
Failed to resolve action download info. Error: Unable to resolve action `knative-sandbox/actions-downstream-test@v1`, unable to find version `v1`
Retrying in 21.604 seconds
Failed to resolve action download info. Error: Unable to resolve action `knative-sandbox/actions-downstream-test@v1`, unable to find version `v1`
Retrying in 27.656 seconds
Error: Unable to resolve action `knative-sandbox/actions-downstream-test@v1`, unable to find version `v1`
```

**Review by slinkydeveloper — COMMENTED** [review]
Can you change the comment here too? https://github.com/knative-sandbox/reconciler-test/blob/main/pkg/test_images/eventshub/event_info.go#L51

**Comment by vaikas** [comment]
@slinkydeveloper good now? Thanks :) 

Also, will need to figure out what this new fun error is now:
```
=== Update Deps for Golang
Go mod tidy and vendor
  go: knative.dev/hack@v0.0.0-20210317214554-58edbdc42966: unrecognized import path "knative.dev/hack": https fetch: Get "https://knative.dev/hack?go-get=1": dial tcp 104.198.14.52:443: i/o timeout
  go: knative.dev/hack@v0.0.0-20210317214554-58edbdc42966: unrecognized import path "knative.dev/hack": https fetch: Get "https://knative.dev/hack?go-get=1": dial tcp 104.198.14.52:443: i/o timeout
```

**Review by slinkydeveloper — APPROVED** [review]
/lgtm

All the downstream failures are caused by the knative.dev outage. In any case, there aren't breaking changes here

**Pull request merged**
